version: '3.8'

services:
  report_generator:
    build: .
    container_name: report_generator
    restart: "no"
    volumes:
      - ./reports:/usr/src/app
    command: python fetch_models.py

  scheduler:
    image: shuklaayush/alpine-cron
    container_name: scheduler
    restart: always
    volumes:
      - ./crontab:/etc/crontabs/root
      - /var/run/docker.sock:/var/run/docker.sock
